Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2024
Var
// Seção de Declarações das variáveis 
 num6 : inteiro
 num7 : inteiro
  res : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("informe dois numeros")
 leia(num6,num7)
 res := num6 * num7
 escreva(res)


Fimalgoritmo